import 'package:flutter/material.dart';

class AppState extends ChangeNotifier {
  static final AppState instance = AppState._();

  AppState._();

  // State Variables
  String _languageCode = 'en';
  bool _isLargeText = false;
  bool _isHighContrast = false;
  String? _currentUserName;

  // Getters
  String get languageCode => _languageCode;
  bool get isLargeText => _isLargeText;
  bool get isHighContrast => _isHighContrast;
  String? get currentUserName => _currentUserName;

  // Actions
  void setLanguage(String code) {
    if (_languageCode != code) {
      _languageCode = code;
      notifyListeners();
    }
  }

  void setLargeText(bool enable) {
    if (_isLargeText != enable) {
      _isLargeText = enable;
      notifyListeners();
    }
  }

  void setHighContrast(bool enable) {
    if (_isHighContrast != enable) {
      _isHighContrast = enable;
      notifyListeners();
    }
  }

  void setCurrentUserName(String? name) {
    if (_currentUserName != name) {
      _currentUserName = name;
      notifyListeners();
    }
  }

  // Translations
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Smart Agriculture',
      'welcome': 'Hello, Farmer!',
      'welcome_back': 'Welcome Back',
      'farm_overview': "Here is your farm's overview",
      'my_farm_view': 'My Farm View',
      'soil_moisture': 'Soil Moisture',
      'soil_temp': 'Soil Temp',
      'soil_npk': 'Soil NPK Levels',
      'optimal': 'Optimal',
      'suitable': 'Suitable',
      'balanced': 'Balanced',
      'home': 'Home',
      'sensors': 'Sensors',
      'chatbot': 'Chatbot',
      'crops': 'Crops',
      'live_updates': 'Live Updates Active',
      'temperature': 'Temperature',
      'nutrient_levels': 'Nutrient Levels (NPK)',
      'nitrogen': 'Nitrogen',
      'phosphorus': 'Phosphorus',
      'potassium': 'Potassium',
      'ai_analysis': 'AI Analysis Complete',
      'analysis_desc': 'Based on soil sensor readings from today.',
      'high_match': 'High Match',
      'moderate_match': 'Moderate Match',
      'excellent_match': 'Excellent Match',
      'settings': 'Settings',
      'my_profile': 'MY PROFILE',
      'my_farm': 'MY FARM',
      'alerts': 'ALERTS',
      'general': 'GENERAL',
      'weather_alert': 'Weather Alert',
      'water_alert': 'Water Alert',
      'crop_tips': 'Crop Tips',
      'price_updates': 'Price Updates',
      'language': 'Language',
      'help_support': 'Help & Support',
      'app_info': 'App Info',
      'save_changes': 'Save Changes',
      'exit_settings': 'Exit Settings',
      'exit_saved': 'Settings saved successfully!',
      'name': 'Name',
      'phone': 'Phone',
      'location': 'Location',
      'farm_size': 'Farm Size',
      'accessibility_options': 'Accessibility Options',
      'large_text': 'Large Text',
      'high_contrast': 'High Contrast',
      'screen_reader': 'Screen Reader',
      'login': 'Login',
      'register': 'Register',
      'village': 'Village',
      'mobile_number': 'Mobile Number',
      'login_with_phone': 'Login with your registered phone number',
      'register_as_farmer': 'Register as Farmer',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'register_here': 'Register here',
      'login_here': 'Login here',
      'invalid_phone': 'Please enter a valid phone number',
      'user_not_found': 'No account found with this phone. Please register first.',
      'phone_already_registered': 'This phone number is already registered.',
      'registration_success': 'Registration successful! You can now login.',
      'smart_agriculture': 'Smart Agriculture',
      'fill_all_fields': 'Please fill name, village and phone number',
    },
    'hi': {
      'app_title': 'स्मार्ट कृषि',
      'welcome': 'नमस्ते, किसान!',
      'welcome_back': 'वापसी पर स्वागत है',
      'farm_overview': 'यहाँ आपके खेत का अवलोकन है',
      'my_farm_view': 'मेरा खेत दृश्य',
      'soil_moisture': 'मिट्टी की नमी',
      'soil_temp': 'मिट्टी का तापमान',
      'soil_npk': 'मिट्टी एनपीके स्तर',
      'optimal': 'इष्टतम',
      'suitable': 'उपयुक्त',
      'balanced': 'संतुलित',
      'home': 'होम',
      'sensors': 'सेंसर',
      'chatbot': 'चैटबॉट',
      'crops': 'फसलें',
      'live_updates': 'लाइव अपडेट सक्रिय',
      'temperature': 'तापमान',
      'nutrient_levels': 'पोषक तत्व स्तर (NPK)',
      'nitrogen': 'नाइट्रोजन',
      'phosphorus': 'फास्फोरस',
      'potassium': 'पोटैशियम',
      'ai_analysis': 'एआई विश्लेषण पूर्ण',
      'analysis_desc': 'आज के मिट्टी सेंसर रीडिंग के आधार पर।',
      'high_match': 'उच्च मेल',
      'moderate_match': 'मध्यम मेल',
      'excellent_match': 'उत्कृष्ट मेल',
      'settings': 'सेटिंग्स',
      'my_profile': 'मेरी प्रोफाइल',
      'my_farm': 'मेरा खेत',
      'alerts': 'अलर्ट',
      'general': 'सामान्य',
      'weather_alert': 'मौसम अलर्ट',
      'water_alert': 'जल अलर्ट',
      'crop_tips': 'फसल सुझाव',
      'price_updates': 'मूल्य अपडेट',
      'language': 'भाषा',
      'help_support': 'सहायता और समर्थन',
      'app_info': 'ऐप जानकारी',
      'save_changes': 'परिवर्तन सहेजें',
      'exit_settings': 'सेटिंग्स से बाहर निकलें',
      'exit_saved': 'सेटिंग्स सफलतापूर्वक सहेजी गईं!',
      'name': 'नाम',
      'phone': 'फ़ोन',
      'location': 'स्थान',
      'farm_size': 'खेत का आकार',
      'accessibility_options': 'सुलभता विकल्प',
      'large_text': 'बड़ा पाठ',
      'high_contrast': 'उच्च कंट्रास्ट',
      'screen_reader': 'स्क्रीन रीडर',
      'login': 'लॉगिन',
      'register': 'रजिस्टर',
      'village': 'गाँव',
      'mobile_number': 'मोबाइल नंबर',
      'login_with_phone': 'अपने रजिस्टर्ड फोन नंबर से लॉगिन करें',
      'register_as_farmer': 'किसान के रूप में रजिस्टर करें',
      'dont_have_account': 'खाता नहीं है?',
      'already_have_account': 'पहले से खाता है?',
      'register_here': 'यहाँ रजिस्टर करें',
      'login_here': 'यहाँ लॉगिन करें',
      'invalid_phone': 'कृपया वैध मोबाइल नंबर दर्ज करें',
      'user_not_found': 'इस नंबर से कोई खाता नहीं मिला। कृपया पहले रजिस्टर करें।',
      'phone_already_registered': 'यह नंबर पहले से रजिस्टर्ड है।',
      'registration_success': 'रजिस्ट्रेशन सफल! अब आप लॉगिन कर सकते हैं।',
      'smart_agriculture': 'स्मार्ट कृषि',
      'fill_all_fields': 'कृपया नाम, गाँव और फोन नंबर भरें',
    },
    'te': {
      'app_title': 'స్మార్ట్ వ్యవసాయం',
      'welcome': 'హలో, రైతు!',
      'welcome_back': 'స్వాగతం',
      'farm_overview': 'మీ పొలం యొక్క అవలోకనం ఇక్కడ ఉంది',
      'my_farm_view': 'నా పొలం వీక్షణ',
      'soil_moisture': 'నేల తేమ',
      'soil_temp': 'నేల ఉష్ణోగ్రత',
      'soil_npk': 'నేల NPK స్థాయిలు',
      'optimal': 'సరైనది',
      'suitable': 'తగినది',
      'balanced': 'సమతుల్యమైనది',
      'home': 'హోమ్',
      'sensors': 'సెన్సార్ల',
      'chatbot': 'చాట్‌బాట్',
      'crops': 'పంటలు',
      'live_updates': 'లైవ్ అప్‌డేట్‌లు యాక్టివ్‌గా ఉన్నాయి',
      'temperature': 'ఉష్ణోగ్రత',
      'nutrient_levels': 'పోషక స్థాయిలు (NPK)',
      'nitrogen': 'నైట్రోజన్',
      'phosphorus': 'భాస్వరం',
      'potassium': 'పొటాషియం',
      'ai_analysis': 'AI విశ్లేషణ పూర్తయింది',
      'analysis_desc': 'నేటి నేల సెన్సార్ రీడింగుల ఆధారంగా.',
      'high_match': 'అధిక సరిపోలిక',
      'moderate_match': 'మితమైన సరిపోలిక',
      'excellent_match': 'అద్భుతమైన సరిపోలిక',
      'settings': 'సెట్టింగ్‌లు',
      'my_profile': 'నా ప్రొఫైల్',
      'my_farm': 'నా వ్యవసాయం',
      'alerts': 'హెచ్చరికలు',
      'general': 'సాధారణ',
      'weather_alert': 'వాతావరణ హెచ్చరిక',
      'water_alert': 'నీటి హెచ్చరిక',
      'crop_tips': 'పంట చిట్కాలు',
      'price_updates': 'ధర నవీకరణలు',
      'language': 'భాష',
      'help_support': 'సహాయం & మద్దతు',
      'app_info': 'యాప్ సమాచారం',
      'save_changes': 'మార్పులను సేవ్ చేయండి',
      'exit_settings': 'నిష్క్రమించు',
      'exit_saved': 'సెట్టింగ్‌లు విజయవంతంగా సేవ్ చేయబడ్డాయి!',
      'name': 'పేరు',
      'phone': 'ఫోన్',
      'location': 'స్థానం',
      'farm_size': 'పొలం పరిమాణం',
      'accessibility_options': 'ప్రాప్యత ఎంపికలు',
      'large_text': 'పెద్ద వచనం',
      'high_contrast': 'అధిక కాంట్రాస్ట్',
      'screen_reader': 'స్క్రీన్ రీడర్',
      'login': 'లాగిన్',
      'register': 'నమోదు',
      'village': 'గ్రామం',
      'mobile_number': 'మొబైల్ నంబర్',
      'login_with_phone': 'మీ నమోదైన ఫోన్ నంబర్‌తో లాగిన్ అవండి',
      'register_as_farmer': 'రైతుగా నమోదు చేయండి',
      'dont_have_account': 'ఖాతా లేదా?',
      'already_have_account': 'ఇప్పటికే ఖాతా ఉందా?',
      'register_here': 'ఇక్కడ నమోదు చేయండి',
      'login_here': 'ఇక్కడ లాగిన్ అవండి',
      'invalid_phone': 'దయచేసి చెల్లుబాటు అయ్యే ఫోన్ నంబర్ నమోదు చేయండి',
      'user_not_found': 'ఈ నంబర్‌తో ఖాతా లేదు. దయచేసి మొదట నమోదు చేయండి.',
      'phone_already_registered': 'ఈ నంబర్ ఇప్పటికే నమోదైంది.',
      'registration_success': 'నమోదు విజయవంతం! ఇప్పుడు మీరు లాగిన్ చేయవచ్చు.',
      'smart_agriculture': 'స్మార్ట్ వ్యవసాయం',
      'fill_all_fields': 'దయచేసి పేరు, గ్రామం మరియు ఫోన్ నంబర్ నమోదు చేయండి',
    },
    'ta': {
      'app_title': 'ஸ்மார்ட் விவசாயம்',
      'welcome': 'வணக்கம், விவசாயி!',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'farm_overview': 'உங்கள் பண்ணையின் கண்ணோட்டம் இங்கே',
      'my_farm_view': 'என் பண்ணை பார்வை',
      'soil_moisture': 'மண் ஈரப்பதம்',
      'soil_temp': 'மண் வெப்பநிலை',
      'soil_npk': 'மண் NPK அளவுகள்',
      'optimal': 'உகந்த',
      'suitable': 'பொருத்தமான',
      'balanced': 'சமநிலை',
      'home': 'முகப்பு',
      'sensors': 'சென்சார்கள்',
      'chatbot': 'சாட்போட்',
      'crops': 'பயிர்கள்',
      'live_updates': 'நேரடி புதுப்பிப்புகள் செயலில்',
      'temperature': 'வெப்பநிலை',
      'nutrient_levels': 'ஊட்டச்சத்து அளவுகள் (NPK)',
      'nitrogen': 'நைட்ரஜன்',
      'phosphorus': 'பாஸ்பரஸ்',
      'potassium': 'பொட்டாசியம்',
      'ai_analysis': 'AI பகுப்பாய்வு முடிந்தது',
      'analysis_desc': 'இன்றைய மண் சென்சர் வாசிப்புகளின் அடிப்படையில்.',
      'high_match': 'உயர் பொருத்தம்',
      'moderate_match': 'மிதமான பொருத்தம்',
      'excellent_match': 'சிறந்த பொருத்தம்',
      'settings': 'அமைப்புகள்',
      'my_profile': 'என் சுயவிவரம்',
      'my_farm': 'என் பண்ணை',
      'alerts': 'எச்சரிக்கைகள்',
      'general': 'பொது',
      'weather_alert': 'வானிலை எச்சரிக்கை',
      'water_alert': 'நீர் எச்சரிக்கை',
      'crop_tips': 'பயிர் உதவிக்குறிப்புகள்',
      'price_updates': 'விலை புதுப்பிப்புகள்',
      'language': 'மொழி',
      'help_support': 'உதவி மற்றும் ஆதரவு',
      'app_info': 'பயன்பாட்டு தகவல்',
      'save_changes': 'மாற்றங்களை சேமிக்கவும்',
      'exit_settings': 'அமைப்புகளிலிருந்து வெளியேறு',
      'exit_saved': 'அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டன!',
      'name': 'பெயர்',
      'phone': 'தொலைபேசி',
      'location': 'இடம்',
      'farm_size': 'பண்ணை அளவு',
      'accessibility_options': 'அணுகல் விருப்பங்கள்',
      'large_text': 'பெரிய உரை',
      'high_contrast': 'உயர் காண்ட்ராஸ்ட்',
      'screen_reader': 'திரை வாசகர்',
      'login': 'உள்நுழை',
      'register': 'பதிவு',
      'village': 'கிராமம்',
      'mobile_number': 'மொபைல் எண்',
      'login_with_phone': 'பதிவுசெய்த தொலைபேசி எண்ணுடன் உள்நுழையவும்',
      'register_as_farmer': 'விவசாயியாக பதிவு செய்யுங்கள்',
      'dont_have_account': 'கணக்கு இல்லையா?',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'register_here': 'இங்கே பதிவு செய்யுங்கள்',
      'login_here': 'இங்கே உள்நுழையவும்',
      'invalid_phone': 'செல்லுபடியான தொலைபேசி எண்ணை உள்ளிடவும்',
      'user_not_found': 'இந்த எண்ணுடன் கணக்கு இல்லை. முதலில் பதிவு செய்யுங்கள்.',
      'phone_already_registered': 'இந்த எண் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.',
      'registration_success': 'பதிவு வெற்றி! இப்போது நீங்கள் உள்நுழையலாம்.',
      'smart_agriculture': 'ஸ்மார்ட் விவசாயம்',
      'fill_all_fields': 'தயவுசெய்து பெயர், கிராமம் மற்றும் தொலைபேசி எண்ணை நிரப்பவும்',
    }
  };

  String getString(String key) {
    return _localizedValues[_languageCode]?[key] ?? _localizedValues['en']![key]!;
  }
}
